[workspace]
resolver = "2"
members = [
	"libs/indexer-db",
	"listener"
]

[workspace.dependencies]
sqlx = { version = "0.8", features = [ "bigdecimal", "chrono", "postgres", "runtime-tokio", "tls-native-tls" ] }

[profile.release]
lto = true
